sudo: required
dist: trusty
language: php

# Versi PHP
php:
  - 7.1

# Branch yang digunakan
branches:
  only:
    - master #-> QA/Staging server
    - develop #-> DevServer

# install Environment di OS
before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl # Permissions
  - sudo mv ./kubectl /usr/local/bin/kubectl # Move to persisten
# Precompile
before_script:

# Main Execution (Build)
script: